
export const tumbleweedConfig = {

    ROLL_SPEED_MIN: 4.0,
    ROLL_SPEED_MAX: 9.0,
    ROTATION_SPEED_MIN: -2.0,
    ROTATION_SPEED_MAX: 2.0,
    ACTIVATION_DISTANCE: 100,
    DEACTIVATION_DISTANCE: 150,
    TARGET_AHEAD_MIN: 50,
    TARGET_AHEAD_MAX: 80,
    TARGET_RANDOMNESS: 0.3,
    INITIAL_SPEED_FACTOR_MIN: 1.0,
    INITIAL_SPEED_FACTOR_MAX: 1.6,
    UPDATE_TARGET_AHEAD_MIN: 40,
    UPDATE_TARGET_AHEAD_MAX: 60,
    UPDATE_DIRECTION_RANDOMNESS: 0.2,
    STEERING_LERP_FACTOR: 0.08,
    STEERING_FORCE_FACTOR: 0.5,
    MAX_SPEED_FACTOR: 1.0,
    WOBBLE_FACTOR: 0.1,
    MIN_VELOCITY_SQ_THRESHOLD: 0.1,
    TERRAIN_ADJUST_THRESHOLD: 1.0,
    GROUND_BOUNCE_FACTOR: 0.7,
GROUND_FOLLOW_SMOOTH_FACTOR: 0.1, // How quickly to follow terrain height. Lower is smoother.
    MAX_DOWNWARD_VELOCITY_CLAMP: -5.0, // Max downward speed to prevent tunneling.
    MIN_UPWARD_PUSH_OFFSET: 0.2,       // Offset above terrain to trigger min upward velocity.
    MIN_UPWARD_VELOCITY_NEAR_GROUND: 0.2, // Min upward speed when very close to ground.

    MASS: 0.3,
    FRICTION: 0.2,
    RESTITUTION: 0.5,
    USE_GRAVITY: true,
    GRAVITY_FORCE: 5.0,

    SCALE_MIN: 0.8,
    SCALE_MAX: 1.2,
    MAIN_GEOMETRY_RADIUS: 1.0,
    MAIN_GEOMETRY_DETAIL: 1,
    MAIN_MATERIAL_COLOR: 0xAD8B60,
    MAIN_MATERIAL_ROUGHNESS: 0.9,
    MAIN_MATERIAL_METALNESS: 0.1,
    MAIN_MATERIAL_WIREFRAME: true,
    INNER_GEOMETRY_RADIUS: 0.8,
    INNER_GEOMETRY_DETAIL: 1,
    INNER_MATERIAL_COLOR: 0x8B6B40,
    INNER_MATERIAL_ROUGHNESS: 0.7,
    INNER_MATERIAL_METALNESS: 0.1,

    OBJECT_TYPE_NAME: 'tumbleweed'
};