export const uiConfig = {
    FADE_DURATION_MS: 300,
    LOADING_HIDE_DELAY_MS: 400,
    PULSE_ANIMATION_DURATION_MS: 1000,
    NOTIFICATION_DURATION_MS: 3000,
    NOTIFICATION_FADE_DURATION_MS: 300,

    OPACITY_VISIBLE: '1',
    OPACITY_HIDDEN: '0',

    SCORE_PREFIX: 'Score: ',
    HIGH_SCORE_PREFIX: 'High Score: ',
    LOADING_TEXT_PREFIX: 'Loading... ',
    LOADING_TEXT_SUFFIX: '%',
    LOCKED_LEVEL_TEXT: 'Locked - Complete previous levels to unlock'
};